comment: false

coverage:
  status:
    project: off
    patch: off

ignore:
  - "FileExplorer/Sources/FileExplorer/PathIterator/DiskPathIterator.swift"
  - "FileExplorer/Tests/**/*"
  - "Utils/Tests/**/*"
  - "Utils/Sources/Utils/Storage/UserDefaults*.swift"
